backend:
  name: git-gateway
  branch: snowlake # Branch to update (optional; defaults to master)

media_folder: "assets/images/blog" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "layout", name: "post", widget: "hidden", default: "blog" }
      - { label: "title", name: "title", widget: "string" }
      - { label: "date", name: "date", widget: "datetime" }
      - { label: "tag", name: "tag", widget: "string" }
      - { label: "categories", name: "categories", widget: "string" }
      - { label: "author", name: "author", widget: "string" }
      - { label: "post_image", name: "post_image", widget: "image" }
      - { label: "badge_color", name: "badge_color", widget: "hidden", default: "bg-meander"}
      - { label: "post_format", name: "post_format", widget: "hidden", default: "general"}
      - { label: "Body", name: "body", widget: "markdown" }